#!/usr/bin/env python3
"""Generate a GPS L5I tracking config for one or more PRNs.

Two RF scenarios were field-tested (see dev_notes/05 and 07); use --scenario to
apply the config that actually worked for each:

  --scenario cable    strong direct-connect feed (CN0 ~70): clean single-sat
                      CNAV decode. single-path + fine doppler step + data tracking.
  --scenario antenna  weak passive-antenna over-air (CN0 ~30, marginal): fine
                      doppler, relaxed CFAR, more dwells, narrower loops. Best
                      effort -- L5 over-air often too weak to decode; position
                      the RX antenna close to the TX.

Key lessons baked in:
  * blocking=auto -> false for real-time UHD. The acquisition worker must keep
    consuming samples during a dwell or the USRP overflows (fixed in
    pcps_acquisition.cc); blocking=false is what exercises that path.
  * doppler_step: use ~100 Hz. A coarse step leaves a large hand-off frequency
    error, which wrecks carrier lock (carrier_lock_test stays low, no NAV).
  * L5 telemetry is CNAV ("New GPS L5 CNAV message received"), not "New GPS NAV".
  * track_pilot=true (L5Q) gives cleaner carrier lock; CNAV is still decoded from
    the L5I data component.

Examples:
  Offline cable decode:
    python3 make_l5_dualpath_conf.py --source file --input cap.dat --prns 23 \
      --rate 20000000 --scenario cable --output /tmp/l5.conf
  Real-time dual-path (multipath), overflow-safe:
    python3 make_l5_dualpath_conf.py --source uhd --prns 18,20 --rate 30000000 \
      --gain 76 --device-args serial=30F4100 --enable-monitor --output /tmp/l5.conf
"""
import argparse
from pathlib import Path


TEMPLATE_HEAD = """; ============================================================================
; GPS L5I multi-satellite tracking config, generated by
; dev_notes/sim/make_l5_dualpath_conf.py.
;
; Dual-path (default): even channel Signal_Path=0 (primary peak),
;                      odd channel  Signal_Path=1 (second acquisition peak).
; Single-path (--single-path): one channel per PRN, primary peak only.
; ============================================================================
; SPDX-License-Identifier: GPL-3.0-or-later

[GNSS-SDR]
GNSS-SDR.internal_fs_sps={rate}
ControlThread.wait_for_flowgraph=false

{signal_source}
SignalConditioner.implementation={signal_conditioner}
DataTypeAdapter.implementation={data_type_adapter}
InputFilter.implementation=Pass_Through
Resampler.implementation=Pass_Through
Resampler.item_type=gr_complex
Resampler.sample_freq_in={rate}
Resampler.sample_freq_out={rate}

Channels_L5.count={channel_count}
Channels_L5.signal_paths={signal_paths}
Channels.in_acquisition={channels_in_acq}
Channel.signal=L5
"""


FILE_SOURCE_TEMPLATE = """SignalSource.implementation=File_Signal_Source
SignalSource.filename={input_file}
SignalSource.item_type={sample_type}
SignalSource.sampling_frequency={rate}
SignalSource.samples=0
SignalSource.repeat=false
SignalSource.enable_throttle_control=false
"""


UHD_SOURCE_TEMPLATE = """SignalSource.implementation=UHD_Signal_Source
SignalSource.item_type=gr_complex
SignalSource.sampling_frequency={rate}
SignalSource.freq={freq}
SignalSource.gain={gain}
SignalSource.subdevice={subdevice}
SignalSource.antenna={ant}
SignalSource.samples=0
SignalSource.dump=false
SignalSource.enable_throttle_control=false
{device_selector}
"""


TEMPLATE_TAIL = """
Acquisition_L5.implementation=GPS_L5i_PCPS_Acquisition
Acquisition_L5.item_type=gr_complex
Acquisition_L5.coherent_integration_time_ms=1
Acquisition_L5.pfa={pfa}
Acquisition_L5.doppler_max={doppler_max}
Acquisition_L5.doppler_step={doppler_step}
Acquisition_L5.max_dwells={max_dwells}
Acquisition_L5.bit_transition_flag=false
Acquisition_L5.blocking={blocking}
Acquisition_L5.multipath_detection={multipath_detection}
Acquisition_L5.multipath_max_delay_chips={max_delay_chips}
Acquisition_L5.multipath_threshold_fraction={threshold_fraction}
Acquisition_L5.dump=false
Acquisition_L5.dump_channel=0
Acquisition_L5.dump_filename=./gps_l5_dualpath_acq

Tracking_L5.implementation=GPS_L5_DLL_PLL_Tracking
Tracking_L5.item_type=gr_complex
Tracking_L5.track_pilot={track_pilot}
Tracking_L5.pll_bw_hz={pll_bw}
Tracking_L5.dll_bw_hz={dll_bw}
Tracking_L5.pll_bw_narrow_hz={pll_bw_narrow}
Tracking_L5.dll_bw_narrow_hz={dll_bw_narrow}
Tracking_L5.order=2
Tracking_L5.early_late_space_chips=0.5
Tracking_L5.extend_correlation_symbols={extend_symbols}
Tracking_L5.enable_fll_pull_in={enable_fll}
Tracking_L5.fll_bw_hz={fll_bw}
Tracking_L5.pull_in_time_s={pull_in_time}
Tracking_L5.carrier_lock_th={carrier_lock_th}
Tracking_L5.cn0_min={cn0_min}
Tracking_L5.dump=false
Tracking_L5.dump_filename=./gps_l5_dualpath_tracking_ch_

TelemetryDecoder_L5.implementation=GPS_L5_Telemetry_Decoder
TelemetryDecoder_L5.dump=false
TelemetryDecoder_L5.dump_mat=false

Observables.implementation=Hybrid_Observables
Observables.stdout=true
Observables.stdout_interval_ms=1000
Observables.dump=true
Observables.dump_extended=true
Observables.dump_filename={observables_dump}

PVT.implementation=RTKLIB_PVT
PVT.positioning_mode=Single
PVT.iono_model=Broadcast
PVT.trop_model=Saastamoinen
PVT.output_rate_ms=100
PVT.display_rate_ms=500
PVT.dump=false
PVT.dump_filename=./gps_l5_dualpath_PVT
PVT.flag_nmea_tty_port=false
PVT.flag_rtcm_server=false

{monitor}
"""


MONITOR_TEMPLATE = """Monitor.enable_monitor=true
Monitor.enable_protobuf=true
Monitor.client_addresses={monitor_address}
Monitor.udp_port={monitor_port}
Monitor.decimation_factor={monitor_decimation}
"""


# Per-scenario presets (field-tested). A key maps to an args attribute; these are
# applied on top of the parsed args (a scenario is a convenience "easy button" --
# use individual flags instead when you need finer control).
SCENARIOS = {
    "cable": {
        "single_path": True,
        "doppler_step": 100,
        "pfa": "0.001",
        "max_dwells": 8,
    },
    "antenna": {
        "single_path": True,
        "doppler_step": 100,
        "pfa": "0.001",
        "max_dwells": 12,
        "pll_bw": 20.0,
        "enable_fll": True,
        "fll_bw": 10.0,
        "pull_in_time": 2.0,
        "carrier_lock_th": 0.5,
        "cn0_min": 20.0,
    },
}


def parse_prns(text):
    prns = []
    for part in text.replace(" ", "").split(","):
        if not part:
            continue
        prn = int(part)
        if prn < 1 or prn > 32:
            raise SystemExit("GPS L5 PRN out of range 1..32: %d" % prn)
        if prn not in prns:
            prns.append(prn)
    if not prns:
        raise SystemExit("--prns must contain at least one PRN")
    return prns


def build_config(args):
    prns = parse_prns(args.prns)
    dual = not args.single_path
    channel_count = len(prns) * (2 if dual else 1)
    signal_paths = 2 if dual else 1
    channels_in_acq = args.channels_in_acq or min(channel_count, 2)
    if channels_in_acq < 1 or channels_in_acq > channel_count:
        raise SystemExit("--channels-in-acq must be in 1..%d" % channel_count)
    if args.source != "file" and args.sample_type != "gr_complex":
        raise SystemExit("--sample-type is currently supported only with --source file")

    # blocking=auto: false for real-time UHD (the acquisition worker keeps consuming
    # samples so the USRP does not overflow), true for file/offline (keep every sample).
    if args.blocking == "auto":
        blocking = "false" if args.source == "uhd" else "true"
    else:
        blocking = args.blocking
    multipath_detection = "false" if args.single_path else "true"
    track_pilot = "true" if args.track_pilot else "false"

    signal_conditioner = "Signal_Conditioner" if args.sample_type == "ishort" else "Pass_Through"
    data_type_adapter = "Ishort_To_Complex" if args.sample_type == "ishort" else "Pass_Through"
    if args.source == "file":
        signal_source = FILE_SOURCE_TEMPLATE.format(input_file=args.input, rate=args.rate, sample_type=args.sample_type)
    else:
        device_selector = ""
        if args.device_args:
            if args.device_args.startswith("serial="):
                device_selector = "SignalSource.device_serial=%s" % args.device_args.split("=", 1)[1]
            else:
                device_selector = "SignalSource.device_address=%s" % args.device_args
        signal_source = UHD_SOURCE_TEMPLATE.format(
            rate=args.rate,
            freq=args.freq,
            gain=args.gain,
            subdevice=args.subdevice,
            ant=args.ant,
            device_selector=device_selector,
        )
    monitor = ""
    if args.enable_monitor:
        monitor = MONITOR_TEMPLATE.format(
            monitor_address=args.monitor_address,
            monitor_port=args.monitor_port,
            monitor_decimation=args.monitor_decimation,
        )

    text = TEMPLATE_HEAD.format(
        rate=args.rate,
        signal_source=signal_source.rstrip(),
        signal_conditioner=signal_conditioner,
        data_type_adapter=data_type_adapter,
        channel_count=channel_count,
        signal_paths=signal_paths,
        channels_in_acq=channels_in_acq,
    )
    channel = 0
    for prn in prns:
        text += "Channel%d.satellite=%d\n" % (channel, prn)
        text += "Channel%d.signal_path=0\n" % channel
        channel += 1
        if dual:
            text += "Channel%d.satellite=%d\n" % (channel, prn)
            text += "Channel%d.signal_path=1\n" % channel
            channel += 1

    text += TEMPLATE_TAIL.format(
        pfa=args.pfa,
        doppler_max=args.doppler_max,
        doppler_step=args.doppler_step,
        max_dwells=args.max_dwells,
        blocking=blocking,
        multipath_detection=multipath_detection,
        max_delay_chips=args.max_delay_chips,
        threshold_fraction=args.threshold_fraction,
        track_pilot=track_pilot,
        pll_bw=args.pll_bw,
        dll_bw=args.dll_bw,
        pll_bw_narrow=args.pll_bw_narrow,
        dll_bw_narrow=args.dll_bw_narrow,
        extend_symbols=args.extend_symbols,
        enable_fll="true" if args.enable_fll else "false",
        fll_bw=args.fll_bw,
        pull_in_time=args.pull_in_time,
        carrier_lock_th=args.carrier_lock_th,
        cn0_min=args.cn0_min,
        observables_dump=args.observables_dump,
        monitor=monitor.rstrip(),
    )
    if args.enable_monitor:
        text = text.replace("Observables.dump=true", "Observables.dump=false")
    return text


def apply_scenario(args):
    preset = SCENARIOS.get(args.scenario)
    if not preset:
        return
    for key, value in preset.items():
        setattr(args, key, value)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--prns", required=True, help="Comma-separated GPS L5 PRNs, e.g. 18,20,21")
    ap.add_argument("--source", choices=("file", "uhd"), default="file", help="Input source type")
    ap.add_argument("--input", default="/tmp/gps_l5_multi.dat", help="Recorded complex64 file")
    ap.add_argument("--output", required=True, help="Output .conf path")
    ap.add_argument("--rate", type=int, default=10000000, help="Sampling rate in sps")
    ap.add_argument("--sample-type", choices=("gr_complex", "ishort"), default="gr_complex",
                    help="File sample type: gr_complex=fc32, ishort=sc16 interleaved IQ")
    ap.add_argument("--freq", type=int, default=1176450000, help="UHD center frequency in Hz")
    ap.add_argument("--gain", type=float, default=76.0, help="UHD gain in dB")
    ap.add_argument("--ant", default="RX2", help="UHD antenna")
    ap.add_argument("--subdevice", default="A:A", help="UHD subdevice (A:A=RF-A, A:B=RF-B)")
    ap.add_argument("--device-args", default="", help="UHD device args, e.g. serial=30F4100")
    ap.add_argument("--channels-in-acq", type=int, default=0, help="Concurrent acquisition channels; default=min(2,count)")
    ap.add_argument("--scenario", choices=tuple(SCENARIOS), default=None,
                    help="Field-tested preset: cable (strong direct) | antenna (weak over-air)")
    ap.add_argument("--single-path", action="store_true",
                    help="Primary-only clean decode: one channel per PRN, no 2nd-path channel, multipath off")
    ap.add_argument("--blocking", choices=("auto", "true", "false"), default="auto",
                    help="Acquisition.blocking; auto=false for uhd (real-time overflow-safe), true for file")
    ap.add_argument("--track-pilot", action="store_true",
                    help="Track L5Q pilot (dataless, cleaner carrier lock; CNAV still decoded from data)")
    ap.add_argument("--extend-symbols", type=int, default=1, help="Coherent integration symbols (pilot<=20, data<=10)")
    ap.add_argument("--enable-fll", action="store_true", help="FLL-assisted pull-in (robust carrier convergence at low CN0)")
    ap.add_argument("--fll-bw", type=float, default=10.0, help="FLL bandwidth Hz (used with --enable-fll / scenario antenna)")
    ap.add_argument("--pull-in-time", type=float, default=2.0, help="FLL pull-in duration seconds")
    ap.add_argument("--carrier-lock-th", type=float, default=0.85, help="Carrier lock-loss threshold (gnss-sdr default 0.85; lower holds weak signals)")
    ap.add_argument("--cn0-min", type=float, default=25.0, help="Min CN0 dB-Hz before loss (gnss-sdr default 25)")
    ap.add_argument("--pll-bw", type=float, default=15.0)
    ap.add_argument("--dll-bw", type=float, default=2.0)
    ap.add_argument("--pll-bw-narrow", type=float, default=4.0)
    ap.add_argument("--dll-bw-narrow", type=float, default=1.0)
    ap.add_argument("--pfa", default="0.001")
    ap.add_argument("--doppler-max", type=int, default=5000)
    ap.add_argument("--doppler-step", type=int, default=250)
    ap.add_argument("--max-dwells", type=int, default=10)
    ap.add_argument("--max-delay-chips", type=float, default=90.0)
    ap.add_argument("--threshold-fraction", type=float, default=0.25)
    ap.add_argument("--observables-dump", default="./gps_l5_dualpath_observables.dat")
    ap.add_argument("--enable-monitor", action="store_true", help="Enable UDP Monitor and disable Observables.dump")
    ap.add_argument("--monitor-address", default="127.0.0.1")
    ap.add_argument("--monitor-port", default="1234")
    ap.add_argument("--monitor-decimation", type=int, default=50)
    args = ap.parse_args()

    apply_scenario(args)
    output = Path(args.output)
    output.write_text(build_config(args), encoding="utf-8")
    print("wrote %s (scenario=%s single_path=%s blocking=%s)"
          % (output, args.scenario, args.single_path, args.blocking))


if __name__ == "__main__":
    main()
